//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Wardrobe_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top
    {
        public int TopID { get; set; }
        [Display(Name ="Top Name")]
        public string TopName { get; set; }
        [Display(Name = "Photo")]
        public string TopPhoto { get; set; }
        [Display(Name = "Type")]
        public string TopType { get; set; }
        [Display(Name = "Color")]
        public string TopColor { get; set; }
        [Display(Name = "Season")]
        public string TopSeason { get; set; }
        [Display(Name = "Occasion")]
        public string TopOccasion { get; set; }
    }
}
